version: "3"
services:

  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-${NACOS_VERSION}
    env_file:
      - ./nacos-standalone-mysql.env
    volumes:
      - ../data/standalone-logs/:/home/nacos/logs
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    env_file:
      - ./mysql.env
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ../data/mysql-init:/docker-entrypoint-initdb.d/
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  # redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"
    volumes:
      - ../data/redis_data:/data
    # 直接使用默认配置，不设置密码
    command: [ "redis-server" ]

  # rocketMQ
  rmqnamesrv:
    image: apache/rocketmq:5.1.4
    hostname: rocketmq
    # restart: always
    container_name: corki-rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  rmqbroker:
    image: apache/rocketmq:5.1.4
    # restart: always
    container_name: corki-rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ../config/rocketmq/broker.conf:/opt/rocketmq-5.1.4/conf/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-5.1.4/conf/broker.conf
    depends_on:
      - rmqnamesrv

  # seata
  seata-server:
    image: seataio/seata-server:2.0.0
    hostname: seata-server
    # restart: always
    container_name: corki-seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file